"""empty message

Revision ID: 792afa54e14b
Revises: 
Create Date: 2020-11-20 10:27:25.851153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792afa54e14b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('document_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Clients')
    # ### end Alembic commands ###
